// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cfjbqjetgqiddkkkfjzm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmamJxamV0Z3FpZGRra2tmanptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUzMzY1NzMsImV4cCI6MjA1MDkxMjU3M30.gli3tBuiX0aW4xFnmwrN6ZE_QC8KJn88pKoWKPZdHio";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);